### ISSUE TITLE
Attempt to retrieving an asset that does not exist throws exception rather than returning null.

### ISSUE THREAD

**Issue by mattnield** [kontent-ai/management-sdk-net#251]
### Brief bug description

When trying to retrieve an `AssetModel` (and other items such as `LanguageVariantModel`), code examples show that a nullable object can be returned ( [see **Retrieve an asset** ]( https://kontent.ai/learn/docs/apis/openapi/management-api-v2/#operation/retrieve-an-asset) ). The assumption here is that if no item is found, then a null item is returned according to the code in the C# sample:

```csharp
// Tip: Find more about .NET SDKs at https://kontent.ai/learn/net
using Kontent.Ai.Management;

var client = new ManagementClient(new ManagementOptions
{
    ApiKey = "<YOUR_API_KEY>",
    ProjectId = "<YOUR_PROJECT_ID>"
});

var identifier = Reference.ById(Guid.Parse("fcbb12e6-66a3-4672-85d9-d502d16b8d9c"));
// var identifier = Reference.ByCodename("which-brewing-fits-you");

var response = await client.GetAssetAsync(identifier);

Assert.NotNull(response);
```

What actually happens is that a `ManagementException` is thrown:

```txt
Unhandled exception. Kontent.Ai.Management.Exceptions.ManagementException: The requested asset '{external id: 035166}' was not found.
   at Kontent.Ai.Management.Modules.HttpClient.ManagementHttpClient.SendAsync(IMessageCreator messageCreator, String endpointUrl, HttpMethod method, HttpContent requestContent, Dictionary`2 headers)
   at Kontent.Ai.Management.Modules.ActionInvoker.ActionInvoker.InvokeReadOnlyMethodAsync[TResponse](String endpointUrl, HttpMethod method, Dictionary`2 headers)
   at Kontent.Ai.Management.ManagementClient.GetAssetAsync(Reference identifier)
```

Is this intended functionality and does the documentation just need to be updated? It's a frustrating pattern, as integration and content migration needs to have an unusually high number of try-catch block to deal with determining if an item exists.

### Test environment

 - Platform/OS: .NET 6,  macOS Ventura 31.5.1
 - Version: Kontent.ai.Management 4.6.0

**Comment by pokornyd** [comment]
shipped in v9 beta. 

the SDK moved to a result pattern: API-level failures, including 404s, no longer throw. `GetAssetAsync` on a missing asset returns a failed result you inspect instead of an exception you catch:

```csharp

 var result = await client.GetAssetAsync(identifier);
 if (!result.IsSuccess)
 {
     // result.StatusCode == HttpStatusCode.NotFound, result.Error has the API's detail
 }
 // or: if (result.TryGetValue(out var asset)) { … }
```

in case exceptions are desirable, `EnsureSuccess()` opts back into throwing.

will close this issue with v9 GA release. check out `vnext` branch for the rewritten SDK docs

**Comment by pokornyd** [comment]
9.0.0 is out, so closing this. 

nothing throws on an API error any more -- 404 included. you can check StatusCode on the API result:

```csharp
var result = await client.GetAssetAsync(identifier);
if (result.StatusCode == HttpStatusCode.NotFound) { ... }

// or
if (result.TryGetValue(out var asset)) { ... }
```

`EnsureSuccess()` opts back into throwing where you'd rather have it.

note that this SDK has moved to a new monorepo: https://github.com/kontent-ai/dotnet , please submit new issues there
